import { env } from '../config/env'

export interface SearchResult {
    id: string
    title: string
    url: string
    displayUrl: string
    snippet: string
    source: 'live' | 'mock'
}

export interface SearchResponse {
    query: string
    mode: 'live' | 'mock'
    results: SearchResult[]
}

function slugify(value: string) {
    return value
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/^-+|-+$/g, '')
        .slice(0, 60) || 'query'
}

function titleCase(value: string) {
    return value
        .split(/\s+/)
        .filter(Boolean)
        .map((part) => part[0].toUpperCase() + part.slice(1))
        .join(' ')
}

function createMockResults(query: string): SearchResult[] {
    const normalized = titleCase(query)
    const slug = slugify(query)
    const domains = [
        'docs.simnet.dev',
        'guide.horizonhub.app',
        'journal.signalweekly.net',
        'forum.stackcity.dev',
        'wiki.cloudatlas.org',
        'labs.novascope.io',
    ]

    return Array.from({ length: 6 }, (_, index) => {
        const url = `https://${domains[index % domains.length]}/${slug}/${index + 1}`
        return {
            id: `mock-${index + 1}`,
            title: `${normalized} result ${index + 1}`,
            url,
            displayUrl: url.replace(/^https?:\/\//, ''),
            snippet: `Mock search result for "${query}" generated by the AetherOS server. Add TAVILY_SEARCH_API_KEY for live web results.`,
            source: 'mock',
        }
    })
}

async function fetchTavilyResults(query: string): Promise<SearchResult[]> {
    const response = await fetch('https://api.tavily.com/search', {
        method: 'POST',
        headers: {
            Accept: 'application/json',
            'Content-Type': 'application/json',
            Authorization: `Bearer ${env.tavilySearchApiKey!}`,
        },
        body: JSON.stringify({
            query,
            topic: 'general',
            search_depth: 'basic',
            max_results: 8,
            include_answer: false,
            include_images: false,
            include_raw_content: false,
        }),
    })

    if (!response.ok) {
        throw new Error(`TAVILY_SEARCH_FAILED:${response.status}`)
    }

    const payload = await response.json() as {
        results?: Array<{
            title?: string
            url?: string
            content?: string
        }>
    }

    return (payload.results ?? [])
        .filter((entry) => entry.title && entry.url)
        .slice(0, 8)
        .map((entry, index) => ({
            id: `live-${index + 1}`,
            title: entry.title!,
            url: entry.url!,
            displayUrl: entry.url!.replace(/^https?:\/\//, ''),
            snippet: entry.content?.trim() || 'No summary available.',
            source: 'live' as const,
        }))
}

export async function searchWeb(query: string): Promise<SearchResponse> {
    const normalizedQuery = query.trim()
    if (!normalizedQuery) {
        return {
            query: normalizedQuery,
            mode: 'mock',
            results: [],
        }
    }

    if (!env.tavilySearchApiKey) {
        return {
            query: normalizedQuery,
            mode: 'mock',
            results: createMockResults(normalizedQuery),
        }
    }

    try {
        const results = await fetchTavilyResults(normalizedQuery)
        if (results.length > 0) {
            return {
                query: normalizedQuery,
                mode: 'live',
                results,
            }
        }
    } catch {
        // Fall through to mock results when the live provider is unavailable.
    }

    return {
        query: normalizedQuery,
        mode: 'mock',
        results: createMockResults(normalizedQuery),
    }
}
